### ISSUE TITLE
Gogs will no longer be deployed

### ISSUE THREAD

**Issue by rbaumgar** [siamaksade/openshift-cd-demo#139]
./provision deploy

+ oc new-app -f https://raw.githubusercontent.com/siamaksade/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml --param=GOGS_VERSION=0.11.34 --param=DATABASE_VERSION=9.6 --param=HOSTNAME=gogs-cicd-user1.apps.cluster-wien-28ce.wien-28ce.example.opentlc.com --param=SKIP_TLS_VERIFY=true
warning: Cannot find git. Ensure that it is installed and in your path. Git is required to work with git repositories.
error: unable to load template file "https://raw.githubusercontent.com/siamaksade/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml": unable to read URL "https://raw.githubusercontent.com/siamaksade/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml", server reported 404 Not Found, status code=404
error: unable to locate any template files with name "https://raw.githubusercontent.com/siamaksade/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml"

repository gogs-openshift-decker does no longer exist. correct: github.com/siamaksade/gogs

**Comment by cmelim** [comment]
I had the same error, the solution is to change the .yml file, rewind the url https://raw.githubusercontent.com/siamaksade/gogs-openshift-docker/master/openshift/gogs-template.yaml and https: // raw.githubusercontent.com/siamaksade/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml for

https://raw.githubusercontent.com/OpenShiftDemos/gogs-openshift-docker/master/openshift/gogs-template.yaml and
https://raw.githubusercontent.com/OpenShiftDemos/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml

Also, if you want to do the installation at this time, I recommend that you change line 171 of the provision.sh file, since this step refers to this repository, what you can do is upload the cicd file to a repo git template.yaml.

**Comment by siamaksade** [comment]
Fixed with 23b96871f18168b80cf92a9a56c1d82437270be6
