### ISSUE TITLE
gogs needs to be installed with postgresql info

### ISSUE THREAD

**Issue by dmhumph** [siamaksade/openshift-cd-demo#23]
Gogs needed to be installed when running for first time.  I had to change the database to postgresql, update the IP address, and add the generated username and password.

I had to run the following command on the gogs postgresql pod to find the generated username and password for initial install:
oc describe pod <podname>

**Comment by siamaksade** [comment]
_install-gogs_ pod runs the install script for Gogs to setup database and passed the db credentials

**Comment by drejmar** [comment]
The command to setup CD/CI components from template:
`oc process -f cicd-template.yaml | oc create -f -`

The first time I ran it, the install-gogs pod failed to do its job, because it tried to use the gogs service before it was functional.
Just delete the install-gogs pod and run the above command again.

**Comment by suibinz** [comment]
following up  on @drejmar , I am not sure what the "correct" way to so it. My hacky way to do so is to delete the "install-gogs" pod (which would have been sitting at replica 0/1 after the initial installation complettion). Then run `oc process -f cicd-template.yaml | oc create -f -` again for oc to deploy the install-gogs pod again.
